= {product} - Hist贸rias de Usuario
Universidad Cat贸lica Boliviana. <ecampohermoso@ucb.edu.bo>
1.0.0
:product: BOT RRHH

## Introducci贸n
El presento documente tendr谩 el detalle de todas las histor铆as de usuario para la construcci贸n deun BOT de RRHH.

Se ha establecido que la funcionalidad m铆nima para la implementaci贸n ser谩:

Para los empleados:

 1. Los empleados pueden solicitar vacaciones mediante el BOT.
 2. El empleado debe poder ver el historial de d铆as soliciatados y cuantos d铆as le queda.

Para el personal de RRHH:

 1. El personal de RRHH debe poder autorizar o rechazar las vacaciones solicitadas.

## Hist贸rias de Usuario.

### 100 - Solicitud de d铆as de vacaci贸n.

*Autor*: Ernesto Campohermoso

*Fecha*: 24/02/2022

*Prioridad*: ALTA

#### Descripci贸n
Un `Empleado` debe solicitar vacaciones por medio de la aplicaci贸n, para esto debe enviar la fecha inicio y fecha fin de la solicitud. Una vez enviada su solicitud una `Encargado de RRHH` proceder谩 a autorizar o rechazar la solicitud del empleado, en caso de que la `Solicitud` sea rechazada se debe agregar una observaci贸n para que si es que procede el empleado realice las modificaciones correspondientes. Adem谩s el `BOT` debe llevar un control de:
 * Los d铆as h谩biles del a帽o
 * La cantidad de d铆as que el empleado ya tomo vacaciones
 * La cantidad de d铆as que le corresponde al empleado por vacaciones, de acuerdo a lo que establece el ministerio de trabajo (ej. las vacaciones son para empleados con m谩s de un a帽o de experiencia, del 2do al 3er a帽o se tienen 15 d铆as de vacaciones, etc.)

La solicitud pasar谩 pos los siguientes estados:

  * *SOLICITADO*: Cuando el usuario env铆a su solicitud al BOT y el BOT no la rechaza.
  * *NO VLIDO*: Cuando el usuario env铆a su solicitud al BOT y no cumple con los requisitos del ministerio de trabajo o el empleado solicita mas d铆as de los que puede.
  * *APROBADO*: Solicitud aprobada por RRHH
  * *RECHAZADO*: Solicitud rechazada por RRHH
  * *CANCELADA*: El usuario cancel贸 una solicitud APROBADA

El diagrama de estados para la `SOLICITUD` ser谩:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

[*] --> SOLICITADO
SOLICITADO --> NO_VALIDO
NO_VALIDO --> [*]
SOLICITADO -> APROBADO
SOLICITADO -> RECHAZADO
RECHAZADO --> [*]
APROBADO -> CANCELADO
APROBADO --> [*]
CANCELADO --> [*]

@enduml
....

#### Escenarios
1. Empleado no esta registrado en la aplicaci贸n.
2. Empleado esta registrado en la aplicaci贸n con dias de vacaci贸n disponibles.
3. Empleado esta registrado en la aplicaci贸n sin d铆as disponibles.
4. Solicitud de permisos.
5. Cancelaci贸n de vacaciones.

#### Casos de Prueba

*100.1.1 Usuario no registrado en la aplicaci贸n* 

Descripci贸n: Un usuario que no esta registrado en el sistema no deber铆a poder ver el menu de opciones para solicitar vacaciones.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "Usted no esta registrado. Para registrarse ejecute el comando /registrar"

### 101 - Registro de usuario en el sistema.

*Autor*: Ernesto Campohermoso

*Fecha*: 03/03/2022

*Prioridad*: MUY ALTA

#### Descripci贸n

Un `Empleado` debe poder solicitar su registro en el sistema por medio del mismo BOT, al momento de solicitar su registro, el empleado deber谩 enviar la siguiente informaci贸n:

 * Nombres
 * Primer apellido
 * Segundo apellido
 * Tercer apellido
 * Fecha de nacimiento 
 * Selfie.
 * N煤mero de documento de identidad.
 * Complemento.

Esta informaci贸n es guardad en BBDD y se coloca al empleado en un estado `REGISTRO SOLICITADO`. Luego el `ADMINISTRADOR DE RRHH` recibe la notificaci贸n con la informaci贸n del empleado y procede a aprobar (`REGISTRO APROBADO`) o denegar `REGISTRO DENEGADO` la solicitud.

El diagrama de secuencias para la presente hist贸ria es el siguiente:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
actor Empleado 

Empleado -> BOT: Solicitar registro en el sistema
BOT --> Empleado: 

actor RRHH
BOT -> RRHH: Nueva solicitud de registro
RRHH --> BOT: Aprobaci贸n/Rechazo
BOT -> Empleado: Notificaci贸n del estado de la solicitud

@enduml
....

#### Escenarios
1. Solicitud APROBADA.
2. Solicitud RECHAZADA.
3. Validaci贸n de datos ingresados por el usuario.

#### Casos de Prueba

*101.1.1 Validaci贸n de par谩metros* 
Descripci贸n: Al momento de registrarse el empleado, los siguientes campos son obligatorios: Nombres, Primer apellido, Fecha de nacimiento, Selfie, N煤mero de documento de identidad.

En caso de que el `Empleado no ingrese uno de estos valores` no se debe proceder a enviar la solicitud.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "Usted no esta registrado. Para registrarse ejecute el comando /registrar"
 2. El `Empleado` env铆a el comando `/registrar`
    - Datos: comando `/registrar`
    - Resultado: El BOT pregunta por el nombre completo
 3. El `Empleado` coloca un espacio en blanco
    - Datos: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente el nombre copmleto porque no puede ser espacios en blanco.
 4. El `Empleado` coloca car谩cteres no convencionales como emojis.
    - Datos: Coloca `Juan Pablo `
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.
